name: data update

on:
  schedule:
    - cron: '58 3 * * *' #UTC

jobs:
  data_update:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: deploy/resources
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: clone
        run: git clone --depth 1 https://github.com/covid19-kitakyushu/covid19-data-updater.git data_setup
      - name: create data
        run: |
          cd $GITHUB_WORKSPACE/data_setup
          npm install
          sleep 120
          node main.js
          sleep 5
      - uses: actions/checkout@v2
        with:
          ref: development
          path: development
      - run: |
          cp -rf $GITHUB_WORKSPACE/data_setup/data.json development/data/
          cp -rf $GITHUB_WORKSPACE/data_setup/inspections_summary.json development/data/
          cp -rf $GITHUB_WORKSPACE/data_setup/inspections_breakdown.json development/data/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: development
          commit-message: BOT; UPDATE DATA
          title: BOT; UPDATE DATA to development
          base: development
          branch: data-bot/development
          labels: auto_merge
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
      - uses: actions/checkout@v2
        with:
          ref: staging
          path: staging
      - run: |
          cp -rf $GITHUB_WORKSPACE/data_setup/data.json staging/data/
          cp -rf $GITHUB_WORKSPACE/data_setup/inspections_summary.json staging/data/
          cp -rf $GITHUB_WORKSPACE/data_setup/inspections_breakdown.json staging/data/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: staging
          commit-message: BOT; UPDATE DATA
          title: BOT; UPDATE DATA to staging
          base: staging
          branch: data-bot/staging
          labels: auto_merge
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - run: |
          cp -rf $GITHUB_WORKSPACE/data_setup/data.json master/data/
          cp -rf $GITHUB_WORKSPACE/data_setup/inspections_summary.json master/data/
          cp -rf $GITHUB_WORKSPACE/data_setup/inspections_breakdown.json master/data/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: master
          commit-message: BOT; UPDATE DATA
          title: BOT; UPDATE DATA to master
          base: master
          branch: data-bot/master
          labels: auto_merge
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
